apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-to-auth-db
  namespace: zt-auth-db
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/zt-auth/sa/auth-service"
