apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: zt-auth-db
  labels:
    app: auth-db
spec:
  serviceName: auth-db
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      serviceAccountName: auth-db
      containers:
        - name: auth-db
          image: devesh11411/blog-auth-db:v1.0.0
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: auth-db-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: blog-auth-db-secrets
                  key: POSTGRES_PASSWORD
          livenessProbe:
            exec:
              command: [pg_isready, -U, authuser, -d, authdb]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: [pg_isready, -U, authuser, -d, authdb]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
