apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: zt-auth
data:
  PORT: "4001"
  SERVICE_NAME: "auth-service"
  PGHOST: "auth-db.zt-auth-db.svc.cluster.local"
  PGPORT: "5432"
  PGUSER: "authuser"
  PGDATABASE: "authdb"
  JWT_EXPIRES_IN: "1h"
  EMAIL_SERVICE_URL: "http://email-service.zt-email.svc.cluster.local:4003"
  FRONTEND_URL: "http://localhost"
  CORS_ORIGIN: "*"
  OTLP_ENDPOINT: "http://jaeger-collector.istio-system.svc.cluster.local:4318/v1/traces"
