apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-to-posts
  namespace: zt-posts
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/zt-posts/sa/waypoint"
