apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-web
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: zero-trust-platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: blog-platform
  source:
    repoURL: https://github.com/DeveshRathod/blog-zero-trust-platform
    targetRevision: main
    path: apps/web
  destination:
    server: https://kubernetes.default.svc
    namespace: zt-web
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
